config/routes.rb
Rails.application.routes.draw do
  root 'statics_pages#home'
  get '/', to: 'statics_pages#home'
  get '/top', to: 'statics_pages#top'
  get '/instructor', to: 'statics_pages#instructor'
  get '/plan', to: 'statics_pages#plan'
  get '/about', to: 'statics_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post 'guest_login', to: 'guest_login#guest'
  post 'admin_login', to: 'guest_login#admin_guest'
  resources :users
  resources :reservations, only: [:index, :new, :create, :destroy]
  resources :menus, only: [:index, :new, :show, :create, :destroy] do
    resources :reviews, only: [:index, :create, :destroy]
  end
  resources :requests, only: [:index, :new, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :reservations
  validates :name, presence: true, length: { maximum: 30 }
  validates :description, presence: true, length: { maximum: 300 }
  validates :price, presence: true
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, only: [:new, :create, :destroy]
  before_action :set_menu, only: [:show, :destroy]

  def index
    @menus = Menu.all
  end

  def new
    @menu = Menu.new
  end

  def show
    @review = Review.new
  end

  def create
    @menu = current_user.menus.build(menu_params)
    if @menu.save
      redirect_to menus_path
      flash[:success] = "メニューが作成されました"
    else
      render 'new'
    end
  end

  def destroy
    @menu.destroy
    flash[:success] = "メニューを削除しました"
    redirect_to menus_path
  end

  private

  def menu_params
    params.require(:menu).permit(:name, :description, :price)
  end

  def set_menu
    @menu = Menu.find(params[:id])
  end
end

app/views/menus/_menu.html.erb
<div class="menu-list">
  <div class="menu-name">
    <h3><%= menu.name %></h3>
  </div>
  <div class="menu-description">
    <span>〜レッスン内容〜</span>
    <p class="menu-lead"><%= menu.description %></p>
    <p class="menu-price">48時間 ￥<%= menu.price %></p>
  </div>
  <div class="menu-btn-link">
    <%= link_to "予約する", new_reservation_path, class: "btn btn-lg btn-primary menu_btn"%>
  </div>
  <div class="reiew-botan-menu">
    <p class="review-link">
      <%= link_to "口コミを書く", menu_path(menu.id), class: "review-right-btn" %>
    </p>
    <p class="review-link">
      <%= link_to "口コミを見る", menu_reviews_path(menu.id) %>
    </p>
    <% if current_user.admin? %>
      <P>
        <%= link_to "メニューを削除する", menu_path(menu.id), method: :delete, class: "menu-delete", data: { confirm: "本当に削除しますか?" } %>
      </p>
    <% end %>
  </div>
</div>

app/views/menus/index.html.erb
<%= provide(:title, "メニュー一覧") %>
<%= render "layouts/login_header" %>
<div class="menu-index">
  <h1>メニュー一覧</h1>
  <% if current_user.admin? %>
    <%= link_to "メニューを追加する", new_menu_path %>
  <% end %>
  <%= render @menus %>
</div>

app/views/menus/new.html.erb
<%= provide(:title, "メニュー作成") %>
<%= render "layouts/login_header" %>
<div class="menu-page">
  <div class="menu-top">
    <h1>メニュー</h1>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @menu, local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name, "メニュー名" %>
        <%= f.text_field :name, class: 'form-control' %> 

        <%= f.label :description, "説明" %>
        <%= f.text_area :description, class: 'form-control' %>

        <%= f.label :price, "値段" %>
        <%= f.text_field :price, class: 'form-control' %> 

        <%= f.submit "メニューを追加する", class: "menu-botan" %>
      <% end %>
      <%= link_to "メニュー一覧はこちら", menus_path, class: "menus-index-botan" %>
    </div>
  </div>
</div>

app/views/menus/show.html.erb
<%= provide(:title, "メニュー詳細") %>
<%= render "layouts/login_header" %>
<div class="menu-page">
  <div class="menu-show">
    <div class="backimage">
      <h1>口コミ</h1>
      <p><%= @menu.name %></p>
      <%= render "reviews/review_form", review: @review, menu: @menu %>
    </div>
  </div>
</div>