config/routes.rb
Rails.application.routes.draw do
  root 'statics_pages#home'
  get '/', to: 'statics_pages#home'
  get '/top', to: 'statics_pages#top'
  get '/instructor', to: 'statics_pages#instructor'
  get '/plan', to: 'statics_pages#plan'
  get '/about', to: 'statics_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post 'guest_login', to: 'guest_login#guest'
  post 'admin_login', to: 'guest_login#admin_guest'
  resources :users
  resources :reservations, only: [:index, :new, :create, :destroy]
  resources :menus, only: [:index, :new, :show, :create, :destroy] do
    resources :reviews, only: [:index, :create, :destroy]
  end
  resources :requests, only: [:index, :new, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :requests, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :menus
  has_many :reviews,  dependent: :destroy
  has_many :reservations, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 30 }
  VALID_EMAIL_REBEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 200 },
                      format: { with: VALID_EMAIL_REBEX },
                  uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]
  before_action :set_user,       only: [:show, :edit]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success]= "登録に成功しました"
      redirect_to top_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "プロフィールが更新されました"
      redirect_to @user
    else
      render 'edit'
      flash.now[:danger] = "編集に失敗しました"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーが削除されました"
    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/views/users/_user.html.erb
<li>
  <div class="users-image">
  <%= image_tag "dj.icon.jpg" %>
  </div>
  <div class="users-content">
  <%= link_to user.name, user, class: "users-name" %>
  <% if current_user.admin? %>
    | <%= link_to "削除する", user, method: :delete, data: { confirm: "本当に削除しますか?" }, class: "delete" %>
  <% end %>
  </div>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<%= render "layouts/login_header" %>
<div class="edit-page">
<h1>プロフィールを編集する</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name, "フルネーム" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email, "メールアドレス" %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password, "パスワード(6文字以上)" %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "パスワード(確認用)" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "編集する", class: "edit-botan" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<%= render "layouts/login_header" %>
<div class="container">
  <%= will_paginate %>

  <div class="user-index">
  <h1>Users</h1>
    <ul class="users">
      <%= render @users %>
    </ul>
  </div>

  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, "新規登録") %>
<%= render 'layouts/header' %>
<div class="signup-page">
  <h1>新規登録</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name, "フルネーム" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email, "メールアドレス" %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password, "パスワード(6文字以上)" %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "パスワード(確認用)" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "アカウントを作成する", class: "signup-botan" %>
      <% end %>
      <%= link_to "ゲストとしてログインする", guest_login_path, method: :post, class: "guest" %>
    </div>
  </div>  
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%= render "layouts/login_header" %>
<div class="user-page">
  <div class="user-image">
  <%= image_tag "dj.icon.jpeg" %> 
  </div>
  <div class="user-name">
    <%= @user.name %> 
  </div>
  <%= link_to "プロフィールを編集する", edit_user_path(current_user), class: "user-botan " %>
</div>