config/routes.rb
Rails.application.routes.draw do
  root 'statics_pages#home'
  get '/', to: 'statics_pages#home'
  get '/top', to: 'statics_pages#top'
  get '/instructor', to: 'statics_pages#instructor'
  get '/plan', to: 'statics_pages#plan'
  get '/about', to: 'statics_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post 'guest_login', to: 'guest_login#guest'
  post 'admin_login', to: 'guest_login#admin_guest'
  resources :users
  resources :reservations, only: [:index, :new, :create, :destroy]
  resources :menus, only: [:index, :new, :show, :create, :destroy] do
    resources :reviews, only: [:index, :create, :destroy]
  end
  resources :requests, only: [:index, :new, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
end

app/controllers/statics_pages_controller.rb
class StaticsPagesController < ApplicationController
  before_action :logged_in_user, only: [:top]
  def home
  end

  def top
  end

  def instructor
  end

  def plan
  end
end

app/views/statics_pages/_top.html.erb
<% provide(:title, "Top") %>
<div class="top-page">
  <div class="top-nav">
    <ul>
    <li class=”current”>
    <%= link_to("Reservation", reservations_path) %></li>
    <li><%= link_to("Plan", menus_path) %></li>
    <li><%= link_to("Instructor", instructor_path) %></li>
    <li><%= link_to("Users Voice", new_request_path) %></li>
    <li><%= link_to("My Page", current_user) %></li>
    </ul>
  </div>
  <div class="top-main">
  </div>
</div>

app/views/statics_pages/about.html.erb
<% provide(:title, "About") %>
<%= render "layouts/header" %> 
<div class="about-container">
  <div class="about-main">
    <h1>About</h1>
  </div>
  <div class="about-item">
    <p>このページは</p>
    <p>E.Y.M DJ SCHOOLの</p>
    <p>Aboutページになります</p>
  </div>
</div>

app/views/statics_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
  <%= render "top" %>
<% else %>
<%= render "layouts/header" %> 
<div class="top">
  <div class="top-container">
    <h1>E.Y.M is Online DJ School</h1>
    <h1>- Enjoy Your Music -</h1>
    <div class="btn-wrapper">
      <%= link_to "ゲストログイン(ゲストユーザー)", guest_login_path, method: :post, class: "botan login" %>
      <%= link_to "ゲストログイン(管理者用)", admin_login_path, method: :post, class: "botan gest-login" %>
    </div>
  </div>
</div>
<div class="message-wrapper">
  <h2>ご自宅でDJデビューしませんか？</h2>
  <h3>STAY HOMEでも音楽は楽しめる！</h3>
  <p>配信の方法やmixの作成など<p>
  <p>DJに必要な要素は全て教えます！</p>
</div>
<%= render 'layouts/footer' %>
<% end %>

app/views/statics_pages/instructor.html.erb
<% provide(:title, "Instructor") %>
<%= render "layouts/login_header" %>
<div class="instructors">
  <div class="instructors-main">
    <div class="instructors-left">
      <div class="instructors-image">
      </div>
    </div>
    <div class="instructors-right">
      <div class="instructors-name">
        <h3>新見 晃司</h3>
        <span>DJ J3ek</span>
      </div>
      <div class="instructors-history">
        <span>〜経歴〜</span>
        <p class="lead">大学入学をきっかけに、DJ活動と音楽制作活動を始める。V2やWOMBなど東京の有名クラブ
        での出演実績もあり。
        </p>
        <span>〜出演実績〜</span>
        <p class="lead">LAUREL TOKYO(渋谷)、VISION(渋谷)、WOMB(渋谷)、MEZZO(六本木)、
        ESPLIT TOKYO(六本木)、V2 TOKYO(六本木)、ORIZURU(新宿)、
        </p>
        <span>〜スキル〜</span>
        <p class="lead">HTML, CSS, Ruby,Ruby on Rails, JavaScript, SQL, Rspec,
          Docker, Git, github, circleCi, AWS, heroku
        </p>
      </div>
    </div>
  </div>
  <div class="instructors-bottom">
  </div>
</div>

app/views/statics_pages/top.html.erb
<%= render "top" %>