config/routes.rb
Rails.application.routes.draw do
  root 'statics_pages#home'
  get '/', to: 'statics_pages#home'
  get '/top', to: 'statics_pages#top'
  get '/instructor', to: 'statics_pages#instructor'
  get '/plan', to: 'statics_pages#plan'
  get '/about', to: 'statics_pages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post 'guest_login', to: 'guest_login#guest'
  post 'admin_login', to: 'guest_login#admin_guest'
  resources :users
  resources :reservations, only: [:index, :new, :create, :destroy]
  resources :menus, only: [:index, :new, :show, :create, :destroy] do
    resources :reviews, only: [:index, :create, :destroy]
  end
  resources :requests, only: [:index, :new, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
end

app/views/layouts/_footer.html.erb
<div class="copyright">
  <p>copyright E.Y.M AllRights Record</p>
</div>
<footer>
  <ul class="flex-list">
    <li class="flex-item">
      <%= link_to "ホーム", top_path %>
    </li>
      <li class="flex-item">
        <%= link_to "予約一覧", reservations_path %>
      </li>
      <li class="flex-item">
        <%= link_to "ユーザー一覧", users_path %>
      </li>
    <li class="flex-item">
      <%= link_to "ログアウト", logout_path, method: :delete, data: {confirm: "ログアウトしますか？"} %>
    </li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="header-left">
      <%= link_to("E.Y.M", root_path, {class: "eym"}) %>
    </div>
    <div class="header-right">
      <%= link_to("About", about_path, {class: "header-item"}) %>
      <%= link_to("新規登録",signup_path, {class: "signup-item"}) %>
      <%= link_to("ログイン", login_path, {class: "login-item"}) %>
    </div>
  </div>
</header>

app/views/layouts/_login_header.html.erb
<div class="login-header"> 
  <div class="header-title">
    <%= link_to("E.Y.M", root_path, {class: "eym"}) %>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> flash"><%= message %></div>
    <% end %>
    <%= yield %>
    <% if logged_in? %>
      <%= render "layouts/footer" %>
    <% end %>
  </body>
</html>